name: SpazioDuels
version: '1.3.0'
main: network.minespazio.spazioduels.SpazioDuelsPlugin
api-version: '1.21'
description: Plugin modular de duelos y KOTH para survival_core
author: SpazioTeam
depend:
  - survival_core
softdepend:
  - PlayerKits2
  - WorldEdit
  - FastAsyncWorldEdit
  - PlaceholderAPI

commands:
  duel:
    description: Comando principal de duelos
    aliases: [duelo, duels]
    usage: /duel <jugador|accept|deny|forfeit|reload>
  duelevent:
    description: Gestiona eventos automaticos de duelos
    aliases: [eventoduel, devent]
    usage: /duelevent <start|cancel|autowin|join|summary>
  spazioduels:
    description: Comando de administracion y setup de SpazioDuels
    aliases: [sd, sduels]
    permission: spazioduels.admin
    usage: /spazioduels <setup|adminkits|kit|reload>
  koth:
    description: Comando de administracion y control de KOTH (King Of The Hill)
    aliases: [kingofthehill]
    usage: /koth <create|delete|setcapdelay|setloot|addcommandreward|removecommandreward|listcommandrewards|setzone|setcapzone|move|start|stop|reload|list|info>
  party:
    description: Sistema de party/equipo para duelos
    aliases: [p, equipo, team]
    usage: /party <create|invite|accept|leave|disband|kick|info>

permissions:
  spazioduels.admin:
    default: op
  spazioduels.admin.event:
    default: op
  spazioduels.admin.koth:
    default: op
